import "bootstrap/dist/css/bootstrap.min.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "THREEC Next.js Web",
  description: "Generated by create next app",
  authors: [{ name: "THREE C", url: "https://github.com/hello-ccchen" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main className="d-flex justify-content-center align-items-center">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
