import "bootstrap/dist/css/bootstrap.min.css";
import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "THREEC Next.js Web",
  description: "Generated by create next app",
  authors: [{ name: "THREE C", url: "https://github.com/hello-ccchen" }],
};

interface IProps {
  children: ReactNode;
}

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main className="d-flex justify-content-center align-items-center">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
