import "bootstrap/dist/css/bootstrap.min.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/core/navbar";
import Footer from "@/components/core/footer";
import AuthProvider from "@/contexts/core/auth-provider";
import { CommonProps } from "@/interfaces/common/common-interface";
import StoreProvider from "@/store/store-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "THREEC Next.js Web",
  description: "Generated by create next app",
  authors: [{ name: "THREE C", url: "https://github.com/hello-ccchen" }],
};

export default function RootLayout({ children }: CommonProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AuthProvider>
            <NavBar />
            <main className="d-flex justify-content-center align-items-center">
              {children}
            </main>
            <Footer />
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
